apiVersion: composition.crossplane.io/v1alpha1
kind: CompositionFunction
metadata:
  name: dynamodb-with-kinesis
spec:
  compositionFunctionType: go-composition
  compositionFunctionSource:
    go:
      functionSourceCodeReference:
        fromSource: true
        sourceCodeDirectory: github.com/7navyasa/function-template-go/fn.go