apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: dynamo-kinesis.example.org
spec:
  group: example.org
  names:
    kind: DynamoKinesisComposite
    plural: dynamokinesis
  claimNames:
    kind: DynamoKinesisClaim
    plural: dynamokinesis
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dynamoDBTable:
                  type: object
                  properties:
                    tableName:
                      type: string
                    billingMode:
                      type: string
                kinesisStream:
                  type: object
                  properties:
                    streamName:
                      type: string
                    shardCount:
                      type: integer
              required:
                - dynamoDBTable
      additionalPrinterColumns:
        - name: TABLE
          type: string
          jsonPath: .spec.dynamoDBTable.tableName
        - name: STREAM
          type: string
          jsonPath: .spec.kinesisStream.streamName